language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email: false
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn install --settings target/travis/settings.xml"
